//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlayerTrack.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PlayerTrack.Resource.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        internal static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Encounters.
        /// </summary>
        internal static string AddEncounters {
            get {
                return ResourceManager.GetString("AddEncounters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Player.
        /// </summary>
        internal static string AddPlayer {
            get {
                return ResourceManager.GetString("AddPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add player manually to your list..
        /// </summary>
        internal static string AddPlayerInstructions {
            get {
                return ResourceManager.GetString("AddPlayerInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Players.
        /// </summary>
        internal static string AddPlayers {
            get {
                return ResourceManager.GetString("AddPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use these symbols to refine your search:.
        /// </summary>
        internal static string AdvancedMatchingExplanation {
            get {
                return ResourceManager.GetString("AdvancedMatchingExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *text*: Match anything containing &apos;text&apos;..
        /// </summary>
        internal static string AdvancedMatchingExplanationContains {
            get {
                return ResourceManager.GetString("AdvancedMatchingExplanationContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *text: Match anything ending with &apos;text&apos;..
        /// </summary>
        internal static string AdvancedMatchingExplanationEnd {
            get {
                return ResourceManager.GetString("AdvancedMatchingExplanationEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to text: Match exactly..
        /// </summary>
        internal static string AdvancedMatchingExplanationExact {
            get {
                return ResourceManager.GetString("AdvancedMatchingExplanationExact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !text: Exclude matches with &apos;text&apos;..
        /// </summary>
        internal static string AdvancedMatchingExplanationExclude {
            get {
                return ResourceManager.GetString("AdvancedMatchingExplanationExclude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to text*: Match anything starting with &apos;text&apos;..
        /// </summary>
        internal static string AdvancedMatchingExplanationStart {
            get {
                return ResourceManager.GetString("AdvancedMatchingExplanationStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Matching for Special Commands.
        /// </summary>
        internal static string AdvancedMatchingTitle {
            get {
                return ResourceManager.GetString("AdvancedMatchingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ago.
        /// </summary>
        internal static string Ago {
            get {
                return ResourceManager.GetString("Ago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alerts.
        /// </summary>
        internal static string Alerts {
            get {
                return ResourceManager.GetString("Alerts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Players.
        /// </summary>
        internal static string AllPlayers {
            get {
                return ResourceManager.GetString("AllPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        internal static string Appearance {
            get {
                return ResourceManager.GetString("Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign Category.
        /// </summary>
        internal static string AssignPlayerCategory {
            get {
                return ResourceManager.GetString("AssignPlayerCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic.
        /// </summary>
        internal static string Automatic {
            get {
                return ResourceManager.GetString("Automatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong. Restart your computer and try again..
        /// </summary>
        internal static string BackupErrorMessage {
            get {
                return ResourceManager.GetString("BackupErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backups.
        /// </summary>
        internal static string Backups {
            get {
                return ResourceManager.GetString("Backups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banned.
        /// </summary>
        internal static string Banned {
            get {
                return ResourceManager.GetString("Banned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blacklist.
        /// </summary>
        internal static string BlackList {
            get {
                return ResourceManager.GetString("BlackList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BL.
        /// </summary>
        internal static string BlackList_Abbreviation {
            get {
                return ResourceManager.GetString("BlackList_Abbreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocked.
        /// </summary>
        internal static string Blocked {
            get {
                return ResourceManager.GetString("Blocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom.
        /// </summary>
        internal static string Bottom {
            get {
                return ResourceManager.GetString("Bottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B.
        /// </summary>
        internal static string Byte {
            get {
                return ResourceManager.GetString("Byte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        internal static string Cancelled {
            get {
                return ResourceManager.GetString("Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        internal static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Name.
        /// </summary>
        internal static string CategoryName {
            get {
                return ResourceManager.GetString("CategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inherited from the category {0}.
        /// </summary>
        internal static string CategorySpecificSetting {
            get {
                return ResourceManager.GetString("CategorySpecificSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Player.
        /// </summary>
        internal static string ClosePlayer {
            get {
                return ResourceManager.GetString("ClosePlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combine Windows.
        /// </summary>
        internal static string CombineWindows {
            get {
                return ResourceManager.GetString("CombineWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        internal static string Confirmation {
            get {
                return ResourceManager.GetString("Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to proceed?.
        /// </summary>
        internal static string ConfirmationQuestion {
            get {
                return ResourceManager.GetString("ConfirmationQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete?.
        /// </summary>
        internal static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will delete synced category. OK?.
        /// </summary>
        internal static string ConfirmUnsync {
            get {
                return ResourceManager.GetString("ConfirmUnsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains.
        /// </summary>
        internal static string Contains {
            get {
                return ResourceManager.GetString("Contains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        internal static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Context Menu.
        /// </summary>
        internal static string ContextMenu {
            get {
                return ResourceManager.GetString("ContextMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contribute.
        /// </summary>
        internal static string Contribute {
            get {
                return ResourceManager.GetString("Contribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most contributions will go towards covering server and coffee costs..
        /// </summary>
        internal static string ContributionUsage {
            get {
                return ResourceManager.GetString("ContributionUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to Clipboard.
        /// </summary>
        internal static string CopyToClipboard {
            get {
                return ResourceManager.GetString("CopyToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        internal static string Created {
            get {
                return ResourceManager.GetString("Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cross-world Linkshell.
        /// </summary>
        internal static string CrossWorldLinkShell {
            get {
                return ResourceManager.GetString("CrossWorldLinkShell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CWLS.
        /// </summary>
        internal static string CrossWorldLinkShell_Abbreviation {
            get {
                return ResourceManager.GetString("CrossWorldLinkShell_Abbreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;ve set up a project on Crowdin for anyone interested..
        /// </summary>
        internal static string CrowdinProject {
            get {
                return ResourceManager.GetString("CrowdinProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Players.
        /// </summary>
        internal static string CurrentPlayers {
            get {
                return ResourceManager.GetString("CurrentPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Title.
        /// </summary>
        internal static string CustomTitle {
            get {
                return ResourceManager.GetString("CustomTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CWLS.
        /// </summary>
        internal static string CWLS {
            get {
                return ResourceManager.GetString("CWLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        internal static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d.
        /// </summary>
        internal static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Category.
        /// </summary>
        internal static string DefaultCategory {
            get {
                return ResourceManager.GetString("DefaultCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inherited from Player Defaults.
        /// </summary>
        internal static string DefaultSetting {
            get {
                return ResourceManager.GetString("DefaultSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Encounters.
        /// </summary>
        internal static string DeleteEncounters {
            get {
                return ResourceManager.GetString("DeleteEncounters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete History.
        /// </summary>
        internal static string DeleteHistory {
            get {
                return ResourceManager.GetString("DeleteHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Players.
        /// </summary>
        internal static string DeletePlayers {
            get {
                return ResourceManager.GetString("DeletePlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Player Settings.
        /// </summary>
        internal static string DeletePlayerSettings {
            get {
                return ResourceManager.GetString("DeletePlayerSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting records now....
        /// </summary>
        internal static string DeleteRecordsInProgress {
            get {
                return ResourceManager.GetString("DeleteRecordsInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted records successfully..
        /// </summary>
        internal static string DeleteRecordsSuccess {
            get {
                return ResourceManager.GetString("DeleteRecordsSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join Discord and choose the &apos;Translator&apos; role to learn more..
        /// </summary>
        internal static string DiscordRoleInfo {
            get {
                return ResourceManager.GetString("DiscordRoleInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        internal static string Display {
            get {
                return ResourceManager.GetString("Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donations are always appreciated but never required..
        /// </summary>
        internal static string DonationsAppreciated {
            get {
                return ResourceManager.GetString("DonationsAppreciated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player already exists..
        /// </summary>
        internal static string DuplicatePlayerError {
            get {
                return ResourceManager.GetString("DuplicatePlayerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        internal static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encounters.
        /// </summary>
        internal static string Encounters {
            get {
                return ResourceManager.GetString("Encounters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exact.
        /// </summary>
        internal static string Exact {
            get {
                return ResourceManager.GetString("Exact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examine Player.
        /// </summary>
        internal static string ExaminePlayer {
            get {
                return ResourceManager.GetString("ExaminePlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here are some examples to help you get started:.
        /// </summary>
        internal static string ExamplesExplanation {
            get {
                return ResourceManager.GetString("ExamplesExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to notes:! =&gt; Find players without any notes..
        /// </summary>
        internal static string ExamplesExplanation1 {
            get {
                return ResourceManager.GetString("ExamplesExplanation1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to notes:* =&gt; Find players with any notes..
        /// </summary>
        internal static string ExamplesExplanation2 {
            get {
                return ResourceManager.GetString("ExamplesExplanation2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fc:uwu =&gt; Find players in the Free Company &apos;uwu&apos;..
        /// </summary>
        internal static string ExamplesExplanation3 {
            get {
                return ResourceManager.GetString("ExamplesExplanation3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examples.
        /// </summary>
        internal static string ExamplesTitle {
            get {
                return ResourceManager.GetString("ExamplesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute.
        /// </summary>
        internal static string Execute {
            get {
                return ResourceManager.GetString("Execute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        internal static string Failed {
            get {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        internal static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Seen.
        /// </summary>
        internal static string FirstSeen {
            get {
                return ResourceManager.GetString("FirstSeen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FL/BL/FC.
        /// </summary>
        internal static string FL_BL_FC {
            get {
                return ResourceManager.GetString("FL_BL_FC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Focus Target Player.
        /// </summary>
        internal static string FocusTargetPlayer {
            get {
                return ResourceManager.GetString("FocusTargetPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For Developers.
        /// </summary>
        internal static string ForDevelopersTitle {
            get {
                return ResourceManager.GetString("ForDevelopersTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For Everyone.
        /// </summary>
        internal static string ForEveryoneTitle {
            get {
                return ResourceManager.GetString("ForEveryoneTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For Translators.
        /// </summary>
        internal static string ForTranslatorsTitle {
            get {
                return ResourceManager.GetString("ForTranslatorsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free Company.
        /// </summary>
        internal static string FreeCompany {
            get {
                return ResourceManager.GetString("FreeCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FC.
        /// </summary>
        internal static string FreeCompany_Abbreviation {
            get {
                return ResourceManager.GetString("FreeCompany_Abbreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friend List.
        /// </summary>
        internal static string FriendList {
            get {
                return ResourceManager.GetString("FriendList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FL.
        /// </summary>
        internal static string FriendList_Abbreviation {
            get {
                return ResourceManager.GetString("FriendList_Abbreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from now.
        /// </summary>
        internal static string FromNow {
            get {
                return ResourceManager.GetString("FromNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GB.
        /// </summary>
        internal static string Gigabyte {
            get {
                return ResourceManager.GetString("Gigabyte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can help submit or proofread translations for PlayerTrack..
        /// </summary>
        internal static string HelpWithTranslation {
            get {
                return ResourceManager.GetString("HelpWithTranslation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High-End Content.
        /// </summary>
        internal static string HighEndContent {
            get {
                return ResourceManager.GetString("HighEndContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        internal static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Homeworld.
        /// </summary>
        internal static string Homeworld {
            get {
                return ResourceManager.GetString("Homeworld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h.
        /// </summary>
        internal static string Hour {
            get {
                return ResourceManager.GetString("Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can search by name or using special commands..
        /// </summary>
        internal static string HowToSearchExplanation {
            get {
                return ResourceManager.GetString("HowToSearchExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to Search.
        /// </summary>
        internal static string HowToSearchTitle {
            get {
                return ResourceManager.GetString("HowToSearchTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon.
        /// </summary>
        internal static string Icon {
            get {
                return ResourceManager.GetString("Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icons.
        /// </summary>
        internal static string Icons {
            get {
                return ResourceManager.GetString("Icons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inherit.
        /// </summary>
        internal static string Inherit {
            get {
                return ResourceManager.GetString("Inherit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integrations.
        /// </summary>
        internal static string Integrations {
            get {
                return ResourceManager.GetString("Integrations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid name..
        /// </summary>
        internal static string InvalidNameError {
            get {
                return ResourceManager.GetString("InvalidNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job.
        /// </summary>
        internal static string Job {
            get {
                return ResourceManager.GetString("Job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep Encounters.
        /// </summary>
        internal static string KeepEncounters {
            get {
                return ResourceManager.GetString("KeepEncounters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from last 90 days.
        /// </summary>
        internal static string KeepEncountersFromLast90Days {
            get {
                return ResourceManager.GetString("KeepEncountersFromLast90Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in high-end content.
        /// </summary>
        internal static string KeepEncountersInHighEndContent {
            get {
                return ResourceManager.GetString("KeepEncountersInHighEndContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in normal content.
        /// </summary>
        internal static string KeepEncountersInNormalContent {
            get {
                return ResourceManager.GetString("KeepEncountersInNormalContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in overworld.
        /// </summary>
        internal static string KeepEncountersInOverworld {
            get {
                return ResourceManager.GetString("KeepEncountersInOverworld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep Players.
        /// </summary>
        internal static string KeepPlayers {
            get {
                return ResourceManager.GetString("KeepPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep Settings for Players.
        /// </summary>
        internal static string KeepPlayerSettings {
            get {
                return ResourceManager.GetString("KeepPlayerSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seen in last 90 days.
        /// </summary>
        internal static string KeepPlayersSeenInLast90Days {
            get {
                return ResourceManager.GetString("KeepPlayersSeenInLast90Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to with any settings.
        /// </summary>
        internal static string KeepPlayersWithAnySettings {
            get {
                return ResourceManager.GetString("KeepPlayersWithAnySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to with categories.
        /// </summary>
        internal static string KeepPlayersWithCategories {
            get {
                return ResourceManager.GetString("KeepPlayersWithCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to with encounters.
        /// </summary>
        internal static string KeepPlayersWithEncounters {
            get {
                return ResourceManager.GetString("KeepPlayersWithEncounters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to with notes.
        /// </summary>
        internal static string KeepPlayersWithNotes {
            get {
                return ResourceManager.GetString("KeepPlayersWithNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seen in last 90 days.
        /// </summary>
        internal static string KeepSettingsForPlayersSeenInLast90Days {
            get {
                return ResourceManager.GetString("KeepSettingsForPlayersSeenInLast90Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to with any settings.
        /// </summary>
        internal static string KeepSettingsForPlayersWithAnySettings {
            get {
                return ResourceManager.GetString("KeepSettingsForPlayersWithAnySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to with categories.
        /// </summary>
        internal static string KeepSettingsForPlayersWithCategories {
            get {
                return ResourceManager.GetString("KeepSettingsForPlayersWithCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to with encounters.
        /// </summary>
        internal static string KeepSettingsForPlayersWithEncounters {
            get {
                return ResourceManager.GetString("KeepSettingsForPlayersWithEncounters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to with notes.
        /// </summary>
        internal static string KeepSettingsForPlayersWithNotes {
            get {
                return ResourceManager.GetString("KeepSettingsForPlayersWithNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KB.
        /// </summary>
        internal static string Kilobyte {
            get {
                return ResourceManager.GetString("Kilobyte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you&apos;re considering a larger feature, please reach out beforehand to discuss..
        /// </summary>
        internal static string LargeFeatureDiscussion {
            get {
                return ResourceManager.GetString("LargeFeatureDiscussion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Location.
        /// </summary>
        internal static string LastLocation {
            get {
                return ResourceManager.GetString("LastLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Seen.
        /// </summary>
        internal static string LastSeen {
            get {
                return ResourceManager.GetString("LastSeen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Updated.
        /// </summary>
        internal static string LastUpdated {
            get {
                return ResourceManager.GetString("LastUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never.
        /// </summary>
        internal static string LastUpdatedNever {
            get {
                return ResourceManager.GetString("LastUpdatedNever", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lvl.
        /// </summary>
        internal static string Level {
            get {
                return ResourceManager.GetString("Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linkshell.
        /// </summary>
        internal static string LinkShell {
            get {
                return ResourceManager.GetString("LinkShell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LS.
        /// </summary>
        internal static string LinkShell_Abbreviation {
            get {
                return ResourceManager.GetString("LinkShell_Abbreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Characters.
        /// </summary>
        internal static string LocalPlayers {
            get {
                return ResourceManager.GetString("LocalPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locations.
        /// </summary>
        internal static string Locations {
            get {
                return ResourceManager.GetString("Locations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock Window Position.
        /// </summary>
        internal static string LockWindowPosition {
            get {
                return ResourceManager.GetString("LockWindowPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock Window Size.
        /// </summary>
        internal static string LockWindowSize {
            get {
                return ResourceManager.GetString("LockWindowSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lodestone.
        /// </summary>
        internal static string Lodestone {
            get {
                return ResourceManager.GetString("Lodestone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lodestone Locale.
        /// </summary>
        internal static string LodestoneLocale {
            get {
                return ResourceManager.GetString("LodestoneLocale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LS.
        /// </summary>
        internal static string LS {
            get {
                return ResourceManager.GetString("LS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        internal static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual.
        /// </summary>
        internal static string Manual {
            get {
                return ResourceManager.GetString("Manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MB.
        /// </summary>
        internal static string Megabyte {
            get {
                return ResourceManager.GetString("Megabyte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge.
        /// </summary>
        internal static string Merge {
            get {
                return ResourceManager.GetString("Merge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge Players.
        /// </summary>
        internal static string MergePlayers {
            get {
                return ResourceManager.GetString("MergePlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t merge a player with themselves..
        /// </summary>
        internal static string MergePlayersDupe {
            get {
                return ResourceManager.GetString("MergePlayersDupe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select players to merge. This will copy over notes, encounters, and history..
        /// </summary>
        internal static string MergePlayersInstructions {
            get {
                return ResourceManager.GetString("MergePlayersInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m.
        /// </summary>
        internal static string Minute {
            get {
                return ResourceManager.GetString("Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name Change Alert.
        /// </summary>
        internal static string NameChangeAlert {
            get {
                return ResourceManager.GetString("NameChangeAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name Color.
        /// </summary>
        internal static string NameColor {
            get {
                return ResourceManager.GetString("NameColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nameplate.
        /// </summary>
        internal static string Nameplate {
            get {
                return ResourceManager.GetString("Nameplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nameplate Color.
        /// </summary>
        internal static string NameplateColor {
            get {
                return ResourceManager.GetString("NameplateColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nameplate Colors.
        /// </summary>
        internal static string NameplateColors {
            get {
                return ResourceManager.GetString("NameplateColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nameplate Conditions.
        /// </summary>
        internal static string NameplateConditions {
            get {
                return ResourceManager.GetString("NameplateConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nameplate Title.
        /// </summary>
        internal static string NameplateTitle {
            get {
                return ResourceManager.GetString("NameplateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Nameplate Color.
        /// </summary>
        internal static string NameplateUseColor {
            get {
                return ResourceManager.GetString("NameplateUseColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Nameplate Color if Dead.
        /// </summary>
        internal static string NameplateUseColorIfDead {
            get {
                return ResourceManager.GetString("NameplateUseColorIfDead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name@World.
        /// </summary>
        internal static string NameWorld {
            get {
                return ResourceManager.GetString("NameWorld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enter a new category.
        /// </summary>
        internal static string NewCategoryHint {
            get {
                return ResourceManager.GetString("NewCategoryHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enter a new tag.
        /// </summary>
        internal static string NewTagHint {
            get {
                return ResourceManager.GetString("NewTagHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No backups found..
        /// </summary>
        internal static string NoBackupsMessage {
            get {
                return ResourceManager.GetString("NoBackupsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placement for players with no category.
        /// </summary>
        internal static string NoCategoryPlacement {
            get {
                return ResourceManager.GetString("NoCategoryPlacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Change.
        /// </summary>
        internal static string NoChange {
            get {
                return ResourceManager.GetString("NoChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No encounters found..
        /// </summary>
        internal static string NoEncountersMessage {
            get {
                return ResourceManager.GetString("NoEncountersMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No history found..
        /// </summary>
        internal static string NoHistoryMessage {
            get {
                return ResourceManager.GetString("NoHistoryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No icons enabled..
        /// </summary>
        internal static string NoIconsEnabledMessage {
            get {
                return ResourceManager.GetString("NoIconsEnabledMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No player characters found..
        /// </summary>
        internal static string NoLocalPlayers {
            get {
                return ResourceManager.GetString("NoLocalPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No players found..
        /// </summary>
        internal static string NoPlayersFound {
            get {
                return ResourceManager.GetString("NoPlayersFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No records to delete..
        /// </summary>
        internal static string NoRecordsToDelete {
            get {
                return ResourceManager.GetString("NoRecordsToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no special perks for donating, except my gratitude..
        /// </summary>
        internal static string NoSpecialPerks {
            get {
                return ResourceManager.GetString("NoSpecialPerks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        internal static string NotApplicable {
            get {
                return ResourceManager.GetString("NotApplicable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        internal static string NotAvailable {
            get {
                return ResourceManager.GetString("NotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now.
        /// </summary>
        internal static string Now {
            get {
                return ResourceManager.GetString("Now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a world..
        /// </summary>
        internal static string NoWorldError {
            get {
                return ResourceManager.GetString("NoWorldError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Records to delete: {0}/{1} ({2}%%).
        /// </summary>
        internal static string NumberOfRecordsToBeDeleted {
            get {
                return ResourceManager.GetString("NumberOfRecordsToBeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only Show Enabled Icons.
        /// </summary>
        internal static string OnlyShowEnabledIcons {
            get {
                return ResourceManager.GetString("OnlyShowEnabledIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only Show Logged In.
        /// </summary>
        internal static string OnlyShowLoggedIn {
            get {
                return ResourceManager.GetString("OnlyShowLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m always open for help with development..
        /// </summary>
        internal static string OpenForDevHelp {
            get {
                return ResourceManager.GetString("OpenForDevHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Lodestone.
        /// </summary>
        internal static string OpenLodestone {
            get {
                return ResourceManager.GetString("OpenLodestone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Player.
        /// </summary>
        internal static string OpenPlayer {
            get {
                return ResourceManager.GetString("OpenPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Player Plate.
        /// </summary>
        internal static string OpenPlayerPlate {
            get {
                return ResourceManager.GetString("OpenPlayerPlate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open PlayerTrack.
        /// </summary>
        internal static string OpenPlayerTrack {
            get {
                return ResourceManager.GetString("OpenPlayerTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Settings.
        /// </summary>
        internal static string OpenSettings {
            get {
                return ResourceManager.GetString("OpenSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Override.
        /// </summary>
        internal static string Override {
            get {
                return ResourceManager.GetString("Override", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overworld.
        /// </summary>
        internal static string Overworld {
            get {
                return ResourceManager.GetString("Overworld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looking to pitch in? Here are a couple of ways you can help out..
        /// </summary>
        internal static string PitchInIntro {
            get {
                return ResourceManager.GetString("PitchInIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player.
        /// </summary>
        internal static string Player {
            get {
                return ResourceManager.GetString("Player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player added successfully..
        /// </summary>
        internal static string PlayerAddedSuccessfully {
            get {
                return ResourceManager.GetString("PlayerAddedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player Defaults.
        /// </summary>
        internal static string PlayerDefaults {
            get {
                return ResourceManager.GetString("PlayerDefaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player Info.
        /// </summary>
        internal static string PlayerInfo {
            get {
                return ResourceManager.GetString("PlayerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player List.
        /// </summary>
        internal static string PlayerList {
            get {
                return ResourceManager.GetString("PlayerList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player Name.
        /// </summary>
        internal static string PlayerName {
            get {
                return ResourceManager.GetString("PlayerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Players.
        /// </summary>
        internal static string Players {
            get {
                return ResourceManager.GetString("Players", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Players by Category.
        /// </summary>
        internal static string PlayersByCategory {
            get {
                return ResourceManager.GetString("PlayersByCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Players by Tag.
        /// </summary>
        internal static string PlayersByTag {
            get {
                return ResourceManager.GetString("PlayersByTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player Stats.
        /// </summary>
        internal static string PlayerStats {
            get {
                return ResourceManager.GetString("PlayerStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player Summary.
        /// </summary>
        internal static string PlayerSummary {
            get {
                return ResourceManager.GetString("PlayerSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player World.
        /// </summary>
        internal static string PlayerWorld {
            get {
                return ResourceManager.GetString("PlayerWorld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preserve Config Window State on Next Load.
        /// </summary>
        internal static string PreserveConfigState {
            get {
                return ResourceManager.GetString("PreserveConfigState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preserve Main Window State on Next Load.
        /// </summary>
        internal static string PreserveMainWindowState {
            get {
                return ResourceManager.GetString("PreserveMainWindowState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previously known as {0}.
        /// </summary>
        internal static string PreviouslyKnownAs {
            get {
                return ResourceManager.GetString("PreviouslyKnownAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previously on {0}.
        /// </summary>
        internal static string PreviouslyOn {
            get {
                return ResourceManager.GetString("PreviouslyOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proximity Alert.
        /// </summary>
        internal static string ProximityAlert {
            get {
                return ResourceManager.GetString("ProximityAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is nearby..
        /// </summary>
        internal static string ProximityAlertMessage {
            get {
                return ResourceManager.GetString("ProximityAlertMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purge.
        /// </summary>
        internal static string Purge {
            get {
                return ResourceManager.GetString("Purge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Players.
        /// </summary>
        internal static string RecentPlayers {
            get {
                return ResourceManager.GetString("RecentPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Players Threshold (in Minutes).
        /// </summary>
        internal static string RecentPlayersThreshold {
            get {
                return ResourceManager.GetString("RecentPlayersThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace Game Title with Category Name.
        /// </summary>
        internal static string ReplaceGameTitleWithCategoryName {
            get {
                return ResourceManager.GetString("ReplaceGameTitleWithCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace Game Title with Custom Title.
        /// </summary>
        internal static string ReplaceGameTitleWithCustomTitle {
            get {
                return ResourceManager.GetString("ReplaceGameTitleWithCustomTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can report any findings through feedback, Discord, or GitHub..
        /// </summary>
        internal static string ReportFindings {
            get {
                return ResourceManager.GetString("ReportFindings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset category name to {0}.
        /// </summary>
        internal static string ResetCategoryTooltip {
            get {
                return ResourceManager.GetString("ResetCategoryTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Lodestone.
        /// </summary>
        internal static string ResetLodestone {
            get {
                return ResourceManager.GetString("ResetLodestone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Players.
        /// </summary>
        internal static string ResetPlayers {
            get {
                return ResourceManager.GetString("ResetPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review the GitHub issues for any bugs or features you want to work on..
        /// </summary>
        internal static string ReviewGitHub {
            get {
                return ResourceManager.GetString("ReviewGitHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run Action.
        /// </summary>
        internal static string RunAction {
            get {
                return ResourceManager.GetString("RunAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run Backup.
        /// </summary>
        internal static string RunBackup {
            get {
                return ResourceManager.GetString("RunBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run Backup Before.
        /// </summary>
        internal static string RunBackupBeforeDataActions {
            get {
                return ResourceManager.GetString("RunBackupBeforeDataActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleanup Backups.
        /// </summary>
        internal static string RunBackupCleanup {
            get {
                return ResourceManager.GetString("RunBackupCleanup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search icons.
        /// </summary>
        internal static string SearchIconsHint {
            get {
                return ResourceManager.GetString("SearchIconsHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use these options to narrow your search:.
        /// </summary>
        internal static string SearchOptionsExplanation {
            get {
                return ResourceManager.GetString("SearchOptionsExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dc: Find players by their data center..
        /// </summary>
        internal static string SearchOptionsExplanationDC {
            get {
                return ResourceManager.GetString("SearchOptionsExplanationDC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (default): Search by name if no option is provided..
        /// </summary>
        internal static string SearchOptionsExplanationDefault {
            get {
                return ResourceManager.GetString("SearchOptionsExplanationDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fc: Find players in a specific Free Company..
        /// </summary>
        internal static string SearchOptionsExplanationFC {
            get {
                return ResourceManager.GetString("SearchOptionsExplanationFC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gender: Search for players by character gender..
        /// </summary>
        internal static string SearchOptionsExplanationGender {
            get {
                return ResourceManager.GetString("SearchOptionsExplanationGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to notes: Look for players with specific notes..
        /// </summary>
        internal static string SearchOptionsExplanationNotes {
            get {
                return ResourceManager.GetString("SearchOptionsExplanationNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to race: Search for players with by character race..
        /// </summary>
        internal static string SearchOptionsExplanationRace {
            get {
                return ResourceManager.GetString("SearchOptionsExplanationRace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tags: Search for players with specific tags..
        /// </summary>
        internal static string SearchOptionsExplanationTags {
            get {
                return ResourceManager.GetString("SearchOptionsExplanationTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to world: Find players by their home world..
        /// </summary>
        internal static string SearchOptionsExplanationWorld {
            get {
                return ResourceManager.GetString("SearchOptionsExplanationWorld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Options.
        /// </summary>
        internal static string SearchOptionsTitle {
            get {
                return ResourceManager.GetString("SearchOptionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search players.
        /// </summary>
        internal static string SearchPlayersHint {
            get {
                return ResourceManager.GetString("SearchPlayersHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start typing....
        /// </summary>
        internal static string SearchPlayersInputHint {
            get {
                return ResourceManager.GetString("SearchPlayersInputHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Type.
        /// </summary>
        internal static string SearchType {
            get {
                return ResourceManager.GetString("SearchType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seen Count.
        /// </summary>
        internal static string SeenCount {
            get {
                return ResourceManager.GetString("SeenCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Category.
        /// </summary>
        internal static string SelectCategory {
            get {
                return ResourceManager.GetString("SelectCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select player to delete.
        /// </summary>
        internal static string SelectPlayerToDelete {
            get {
                return ResourceManager.GetString("SelectPlayerToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select player to update.
        /// </summary>
        internal static string SelectPlayerToUpdate {
            get {
                return ResourceManager.GetString("SelectPlayerToUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Categories.
        /// </summary>
        internal static string ShowCategories {
            get {
                return ResourceManager.GetString("ShowCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Category Separator.
        /// </summary>
        internal static string ShowCategorySeparator {
            get {
                return ResourceManager.GetString("ShowCategorySeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show/Hide PlayerTrack.
        /// </summary>
        internal static string ShowHidePlayerTrack {
            get {
                return ResourceManager.GetString("ShowHidePlayerTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show/Hide PlayerTrack Settings.
        /// </summary>
        internal static string ShowHidePlayerTrackConfig {
            get {
                return ResourceManager.GetString("ShowHidePlayerTrackConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show in Content.
        /// </summary>
        internal static string ShowInContent {
            get {
                return ResourceManager.GetString("ShowInContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show in High End Content.
        /// </summary>
        internal static string ShowInHighEndContent {
            get {
                return ResourceManager.GetString("ShowInHighEndContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show in Overworld.
        /// </summary>
        internal static string ShowInOverworld {
            get {
                return ResourceManager.GetString("ShowInOverworld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Open Lodestone.
        /// </summary>
        internal static string ShowOpenLodestone {
            get {
                return ResourceManager.GetString("ShowOpenLodestone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Open PlayerTrack.
        /// </summary>
        internal static string ShowOpenPlayerTracker {
            get {
                return ResourceManager.GetString("ShowOpenPlayerTracker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Player Count in Filter.
        /// </summary>
        internal static string ShowPlayerCountInFilter {
            get {
                return ResourceManager.GetString("ShowPlayerCountInFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Player Filter.
        /// </summary>
        internal static string ShowPlayerFilter {
            get {
                return ResourceManager.GetString("ShowPlayerFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Search Box.
        /// </summary>
        internal static string ShowSearchBox {
            get {
                return ResourceManager.GetString("ShowSearchBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Tags.
        /// </summary>
        internal static string ShowTags {
            get {
                return ResourceManager.GetString("ShowTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up for test releases to help find bugs before they go live..
        /// </summary>
        internal static string SignUpTest {
            get {
                return ResourceManager.GetString("SignUpTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will add players found on social lists to PlayerTrack. With this unchecked, only players already in your list will be updated..
        /// </summary>
        internal static string SocialListAddPlayersHelpText {
            get {
                return ResourceManager.GetString("SocialListAddPlayersHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign a category of your choosing when a new player is added to a social list. The player won&apos;t be automatically removed if they leave the social list..
        /// </summary>
        internal static string SocialListDefaultCategoryHelpText {
            get {
                return ResourceManager.GetString("SocialListDefaultCategoryHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social Lists.
        /// </summary>
        internal static string SocialLists {
            get {
                return ResourceManager.GetString("SocialLists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep list automatically synced with a category. These are special categories that you can&apos;t add/remove from manually..
        /// </summary>
        internal static string SocialListSyncCategoryHelpText {
            get {
                return ResourceManager.GetString("SocialListSyncCategoryHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social Lists update at specific times. All lists will refresh when you open their respective screen. In addition, the Friends and Blacklist will update on login. For large Free Companies, ensure you open and fully load each of the three pages in the bottom right to update the list..
        /// </summary>
        internal static string SocialListWarning {
            get {
                return ResourceManager.GetString("SocialListWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Executor.
        /// </summary>
        internal static string SQLExecutor {
            get {
                return ResourceManager.GetString("SQLExecutor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only PRAGMA and SELECT statements are allowed..
        /// </summary>
        internal static string SQLExecutorRestriction {
            get {
                return ResourceManager.GetString("SQLExecutorRestriction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This helps ensure a stable experience for everyone..
        /// </summary>
        internal static string StableExperience {
            get {
                return ResourceManager.GetString("StableExperience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starts With.
        /// </summary>
        internal static string StartsWith {
            get {
                return ResourceManager.GetString("StartsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Want to Support Further?.
        /// </summary>
        internal static string SupportFurtherTitle {
            get {
                return ResourceManager.GetString("SupportFurtherTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync with Dynamic Category.
        /// </summary>
        internal static string SyncWithCategory {
            get {
                return ResourceManager.GetString("SyncWithCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync with Visibility.
        /// </summary>
        internal static string SyncWithVisibility {
            get {
                return ResourceManager.GetString("SyncWithVisibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        internal static string Tags {
            get {
                return ResourceManager.GetString("Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Player.
        /// </summary>
        internal static string TargetPlayer {
            get {
                return ResourceManager.GetString("TargetPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TB.
        /// </summary>
        internal static string Terabyte {
            get {
                return ResourceManager.GetString("Terabyte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top.
        /// </summary>
        internal static string Top {
            get {
                return ResourceManager.GetString("Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to click to remove category from this player.
        /// </summary>
        internal static string UnassignCategoryTooltip {
            get {
                return ResourceManager.GetString("UnassignCategoryTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a dynamic category and can&apos;t be manually unassigned..
        /// </summary>
        internal static string UnassignDynamicCategoryTooltip {
            get {
                return ResourceManager.GetString("UnassignDynamicCategoryTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unavailable.
        /// </summary>
        internal static string Unavailable {
            get {
                return ResourceManager.GetString("Unavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unverified.
        /// </summary>
        internal static string Unverified {
            get {
                return ResourceManager.GetString("Unverified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrade.
        /// </summary>
        internal static string Upgrade {
            get {
                return ResourceManager.GetString("Upgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verified.
        /// </summary>
        internal static string Verified {
            get {
                return ResourceManager.GetString("Verified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visibility.
        /// </summary>
        internal static string Visibility {
            get {
                return ResourceManager.GetString("Visibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visibility Type.
        /// </summary>
        internal static string VisibilityType {
            get {
                return ResourceManager.GetString("VisibilityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voidlist.
        /// </summary>
        internal static string Voidlist {
            get {
                return ResourceManager.GetString("Voidlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: This is the danger zone. These actions cannot be undone!.
        /// </summary>
        internal static string WarningZone {
            get {
                return ResourceManager.GetString("WarningZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whitelist.
        /// </summary>
        internal static string Whitelist {
            get {
                return ResourceManager.GetString("Whitelist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window.
        /// </summary>
        internal static string Window {
            get {
                return ResourceManager.GetString("Window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World Transfer Alert.
        /// </summary>
        internal static string WorldTransferAlert {
            get {
                return ResourceManager.GetString("WorldTransferAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
